### ISSUE TITLE
Linux only?

### ISSUE THREAD

**Issue by rainbowdesign** [kivy/audiostream#13]
`Hello, i took a look at the install file and found:

include_dirs = ['/usr/include/SDL']

It looks very much like it would not work with windows related to the sdl paths:

https://github.com/kivy/audiostream/issues/7

**Comment by rainbowdesign** [comment]
Essentially i got it working now by installing a new debian vm and adding all the requirements manually.
It took quite a long time, and the module seems now not very promising since its nearly undocumentated.

**Comment by rainbowdesign** [comment]
Essentially i got it working now by installing a new debian vm and adding all the requirements manually.
It took quite a long time, and the module seems now not very promising since its nearly undocumentated.

**Comment by 2n2u** [comment]
I'm encountering the same problem sadly. Any workaround instead of using a VM?

**Comment by riku2015** [comment]
i managed to compile in windows, got sdl libraries. all went ok. installation was ok, however when i try use module:
 Traceback (most recent call last):
   File "main.py", line 30, in <module>
     from audiostream import get_output, AudioSample
   File "C:\Python37\lib\site-packages\audiostream\__init__.py", line 19, in <module>
     from audiostream.core import *
 ImportError: DLL load failed: The specified module could not be found.

there is not much info what module is missing?!?
