### ISSUE TITLE
failed install on mac

### ISSUE THREAD

**Issue by paladinic** [kivy/audiostream#52]
Hi,
I am attempting to install `audiostream` using, on my Mac (OS Ventura 13.5.2):
`pip install git+https://github.com/kivy/audiostream.git`

I get the following error.

```
Building wheels for collected packages: audiostream
  Building wheel for audiostream (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      Compiling audiostream/platform/plat_mac.pyx because it changed.
      [1/1] Cythonizing audiostream/platform/plat_mac.pyx
      /Users/USER/anaconda3/lib/python3.11/site-packages/Cython/Compiler/Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/nc/k8_d0krn429dlxj8p5b1z7pc0000gn/T/pip-req-build-7q4uztmh/audiostream/platform/plat_mac.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: audiostream/platform/../config.pxi:1:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if py_audio_callback is None:
                  return
              py_audio_callback(buf[:buffersize])
      
      cdef void init():
          audiostream_cy_register(cy_audio_callback)
                                  ^
      ------------------------------------------------------------
      
      audiostream/platform/plat_mac.pyx:36:28: Cannot assign type 'void (char *, int) except * nogil' to 'audio_callback_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (char *, int) except * nogil'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/nc/k8_d0krn429dlxj8p5b1z7pc0000gn/T/pip-req-build-7q4uztmh/setup.py", line 103, in <module>
          setup(
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/Users/USER/anaconda3/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: audiostream/platform/plat_mac.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for audiostream
  Running setup.py clean for audiostream
Failed to build audiostream
ERROR: Could not build wheels for audiostream, which is required to install pyproject.toml-based projects
```

I tried following the advice given [here](https://github.com/kivy/audiostream/issues/23)

```
>sudo apt-get install libsdl1.2-dev
>sudo apt-get install libsdl-mixer1.2-dev
```

...which [apparently](https://stackoverflow.com/questions/47295218/install-sdl2-in-mac) on mac is something like:

```
brew install SDL2
brew install SDL2_image
brew install SDL2_ttf
brew install sdl2_mixer  
```

...but alas, I still get the error.

**Comment by Julian-O** [comment]
👋 We use the issue tracker exclusively for bug reports and feature requests.
However, this issue appears to be a support request. Please use our   [support channels](https://github.com/kivy/kivy/blob/master/README.md#support)            to get help with the project.
            
Let us know if this comment was made in error, and we'll be happy to reopen the issue.
